# Generated by Django 5.2.6 on 2025-09-17 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('framework_type', models.CharField(choices=[('gdpr', 'GDPR (EU General Data Protection Regulation)'), ('ccpa', 'CCPA (California Consumer Privacy Act)'), ('popia', 'POPIA (Protection of Personal Information Act - South Africa)'), ('coppa', "COPPA (Children's Online Privacy Protection Act)"), ('ferpa', 'FERPA (Family Educational Rights and Privacy Act)'), ('pipeda', 'PIPEDA (Personal Information Protection and Electronic Documents Act - Canada)'), ('custom', 'Custom Framework')], max_length=20)),
                ('description', models.TextField()),
                ('applicable_regions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Implementation'), ('inactive', 'Inactive'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('implementation_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_owner_managed', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('data_access', 'Data Access'), ('data_modification', 'Data Modification'), ('data_deletion', 'Data Deletion'), ('consent_change', 'Consent Change'), ('policy_update', 'Policy Update'), ('export_request', 'Data Export Request'), ('deletion_request', 'Data Deletion Request')], max_length=20)),
                ('action_description', models.TextField()),
                ('data_fields_accessed', models.JSONField(default=list)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('under_review', 'Under Review'), ('remediated', 'Remediated')], default='compliant', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_automation.complianceframework')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Compliance Report'), ('quarterly', 'Quarterly Assessment'), ('annual', 'Annual Compliance Review'), ('incident', 'Incident Report'), ('audit', 'External Audit Report'), ('custom', 'Custom Report')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('summary', models.TextField()),
                ('detailed_findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('compliance_score', models.FloatField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='compliance_reports/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_automation.complianceframework')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ConsentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data_processing', 'Data Processing'), ('marketing', 'Marketing Communications'), ('cookies', 'Cookie Usage'), ('third_party_sharing', 'Third-Party Data Sharing'), ('analytics', 'Analytics and Tracking'), ('educational_records', 'Educational Records Access')], max_length=30)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=20)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('consent_text', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_automation.complianceframework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('user_profiles', 'User Profiles'), ('educational_records', 'Educational Records'), ('financial_records', 'Financial Records'), ('communication_logs', 'Communication Logs'), ('system_logs', 'System Logs'), ('backup_data', 'Backup Data'), ('analytics_data', 'Analytics Data')], max_length=30)),
                ('retention_period', models.PositiveIntegerField()),
                ('retention_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], max_length=10)),
                ('description', models.TextField()),
                ('automated_deletion', models.BooleanField(default=True)),
                ('notification_before_deletion', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance_automation.complianceframework')),
            ],
            options={
                'ordering': ['data_type', 'retention_period'],
            },
        ),
        migrations.CreateModel(
            name='LegalDisclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('disclaimer_type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('cookie_policy', 'Cookie Policy'), ('data_processing_notice', 'Data Processing Notice'), ('parental_consent', 'Parental Consent Notice'), ('educational_records', 'Educational Records Disclaimer')], max_length=30)),
                ('country_code', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('language_code', models.CharField(default='en', max_length=5)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('requires_acceptance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddIndex(
            model_name='complianceframework',
            index=models.Index(fields=['framework_type', 'status'], name='compliance__framewo_4f5a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceframework',
            index=models.Index(fields=['status', 'implementation_date'], name='compliance__status_41a5db_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['audit_type', 'timestamp'], name='compliance__audit_t_56f8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['user', 'timestamp'], name='compliance__user_id_b71b41_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['framework', 'compliance_status'], name='compliance__framewo_818895_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['framework', 'report_type'], name='compliance__framewo_e9cc40_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['status', 'period_end'], name='compliance__status_a7c2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='consentmanagement',
            index=models.Index(fields=['user', 'status'], name='compliance__user_id_a18d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='consentmanagement',
            index=models.Index(fields=['framework', 'consent_type'], name='compliance__framewo_34eaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='consentmanagement',
            index=models.Index(fields=['status', 'expires_at'], name='compliance__status_0910e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consentmanagement',
            unique_together={('user', 'consent_type', 'framework', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='dataretentionpolicy',
            unique_together={('data_type', 'framework')},
        ),
        migrations.AddIndex(
            model_name='legaldisclaimer',
            index=models.Index(fields=['country_code', 'is_active'], name='compliance__country_cefe31_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldisclaimer',
            index=models.Index(fields=['disclaimer_type', 'effective_date'], name='compliance__disclai_ba85d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legaldisclaimer',
            unique_together={('disclaimer_type', 'country_code', 'language_code', 'version')},
        ),
    ]
